<%@ Page Title="Contact" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Contact.aspx.cs" Inherits="CertificateGenerator.Contact" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <link href="Content/CertificateGenerator.css" rel="stylesheet" />
    <div class="main-container">
        <h2>Contact Registrar's Office</h2>
        <p>If you have questions regarding your academic records or the certificates generated by this system, please reach out to us.</p>

        <address>
            <strong>Adventist University of Central Africa</strong><br />
            Masoro Campus, Kigali - Rwanda<br />
            <abbr title="Phone">P:</abbr> (+250) 724 796 996 / 788 473 035
        </address>

        <address>
            <strong>Registrar Email:</strong>   <a href="mailto:registrar@auca.ac.rw">registrar@auca.ac.rw</a><br />
            <strong>Academic Records:</strong> <a href="mailto:juvenal.nsengiyumva@auca.ac.rw">juvenal.nsengiyumva@auca.ac.rw</a>
        </address>
    </div>
</asp:Content>
